title: Javier Chouza's portfolio
description: Basic portfolio of relevant proyects I have done
theme: jekyll-theme-midnight
author:
  name: Javier Chouza Picallo
  email: javierchouzapicallo@gmail.com
