title: Javier Chouza's portfolio
description: Welcome to my portfolio! Here are some interesting projects I have worked on
theme: jekyll-theme-midnight
author:
  name: Javier Chouza Picallo
  email: javierchouzapicallo@gmail.com